name: Build Armbian

on:
  release:
    types: published
  push:
    branches:
      - main
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: started

env:
  RELEASE_SOURCE_TAG: v24.05
  BUILD_MINIMAL: yes
  BUILD_ONLY: default
  KERNEL_CONFIGURE: no
  BOARD: odroidc4
  BRANCH: current
  RELEASE: bookworm
  BUILD_DESKTOP: no

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Download source code
      run: |
        git clone --depth=1 --branch=$RELEASE_SOURCE_TAG https://github.com/armbian/build

    - name: Build Armbian
      id: build
      run: |
        cd build
        ./compile.sh BUILD_MINIMAL=$BUILD_MINIMAL BUILD_ONLY=$BUILD_ONLY KERNEL_CONFIGURE=$KERNEL_CONFIGURE BOARD=$BOARD BRANCH=$BRANCH RELEASE=$RELEASE BUILD_DESKTOP=$BUILD_DESKTOP FORCE_USE_RAMDISK=yes USE_CCACHE=yes
        echo "::set-output name=status::success"
        cd output/images
        tar -cjvf /tmp/Armbian.tar.bz2 *.img
        cd ../..

    - name: Upload Armbian image
      uses: actions/upload-artifact@master
      if: steps.build.outputs.status == 'success'
      with:
        name: Armbian_firmware
        path: /tmp/Armbian.tar.bz2
